config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :users

  get '/thanks', to: 'pages#thanks'
  get '/privacypolicy', to: 'pages#privacypolicy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email_address, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def thanks
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to thanks_path
      flash.alert = "User successfully created"
    else
      flash.alert = "Error"
      render :new
    end
  end

  private

  def user_params
    userParams = params.require(:user).permit(:email_address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      <% if content_for? :title %>
        <%= yield :title %>
      <% else %>
        MatchBooster | No Tinder Matches? Get More Matches On Tinder
      <% end %>
    </title>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145748865-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-145748865-1');
    </script>

    <meta name="description" content=
      <% if content_for? :description %>
        <%= yield :description %>
      <% else %>
        "No matches on Tinder? MatchBooster helps boost your matches & likes on Tinder | Our smart script helps you get more tinder matches!"
      <% end %>
    >
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <script>
    const initUpdateNavbarOnScroll = () => {
      const navbar = document.querySelector('.navi');
      if (navbar) {
        window.addEventListener('scroll', () => {
          if (window.scrollY >= window.innerHeight / 6){
            navbar.classList.add('pink');
          } else {
            navbar.classList.remove('pink');
          }
        });
      }
    }

  </script>
</html>

app/views/pages/privacypolicy.html.erb
<div class="privacy-home">
  <a href="/">Back to Home</a>
</div>
<div class="privacy">

  <h2>PRIVACY POLICY</h2>
  <br>
  <h2>Cookie & Privacy Policy</h2>
  <br>
  <h2>COOKIES ON MATCHBOOSTER.LIVE</h2>
  <br>

  <p>
  The MATCHBOOSTER website, like many others, uses cookies to analyse how anonymous users interact with our website and allow us to improve it. Find out more about our use of cookies below and how you can control them by changing your internet browser settings.
  </p>

  <br><br>
  <h2>WHAT ARE COOKIES?</h2>
  <br>
  <p>
    In a nutshell (forgive the pun) ‘Cookies’ are small text files stored by your browser (e.g. Google Chrome or Firefox) on your desktop, tablet or mobile phone. These small text files allow the websites you visit to store such things as user preferences. For example, when you return to a website you have already signed into once that day and it doesn’t then require you to login again. Effectively the “cookie” has remembered you already logged in so keeps your user session running in the background. That saves you the hassle of logging in multiple times. It is only when you close your browser. If you would like to read more about cookies, wikipedia has a very useful page on them: https://en.wikipedia.org/wiki/HTTP_cookie.
  </p>
  <br>
  <h2>HOW DOES MATCHBOOSTER.LIVE USE COOKIES?</h2>
  <br>

  <p>
  MATCHBOOSTER.LIVE only uses anonymous analytics cookies. Every time a user visits our website third party web analytics (think Google analytics) generates an anonymous cookie that tells use whether you are a new or returning user, what part of the world you come from and how long you spent on our site.
  </p>

  <br>

  <p>
  The upshot is that these cookies allow us to track how many unique users are visiting the site and how often and that helps us to develop our website to make it more relevant, for example, to Google searches. We can make very clear that these cookies cannot be used to identify specific individuals and are used solely by us to ensure that we’re getting through to our target audience effectively. HOW DO I TURN COOKIES OFF? It is possible and in fact very easy to stop your browser accepting cookies, or to stop it accepting cookies from a particular website including this one. All modern browsers allow you to change your cookie settings and usually this will be very obvious under your ‘privacy settings’. Simply tick the box or click the setting that says turn off cookies. If they are not listed under ‘settings’ then they can usually be found in the ‘options’ or ‘preferences’ menu of your browser. If in doubt go to the ‘help’ section of your browser or type into Google “how to switch off cookies on [enter browser name e.g. google chrome”. We hope you enjoy looking at our website and if you are in the market for cutting edge web and mobile development you are in the right place.
  </p>

</div>

app/views/pages/thanks.html.erb
<div class="signup">
  <%= image_tag 'logo.png' %>
  <h1>Thank you for signing up!</h1>
  <h2>We will send you instructions soon.</h2>
</div>
<div class="footer">
  <p>With <i class="fas fa-heart"></i> from Shoreditch </p>
</div>

app/views/users/new.html.erb
<div class="navi">
  <%= image_tag 'logo.png', alt: "MatchMaker logo | Boost Tinder Matches" %>
  <div>
    <h1>MatchBooster</h1>
    <h2 style="font-size: 1.25rem;">Get More Tinder Matches</h2>
  </div>
</div>

<div class="home">
  <h1>Go on more dates! Match with more people! Find the one!</h1>
  <%= simple_form_for(@user) do |f| %>
    <%= f.input :email_address, label: false, placeholder: "Email Address" %>
    <%= f.submit "Subscribe" %>
  <% end %>
</div>

<div class="how-it-works">
  <%= image_tag 'notindermatches.png' %>
  <div class="how-it-works_content">
    <h1>No Tinder Matches?</h1>
    <h2>Using AI we can increase your matches exponentially. Join us! </h2>
    <%= simple_form_for(@user) do |f| %>
      <%= f.input :email_address, label: false, placeholder: "Email Address" %>
      <%= f.submit "Subscribe" %>
    <% end %>
  </div>
</div>

<div class="how-it-works-2">
  <div class="how-it-works_content">
    <h1>Only for $7.99 a Month</h1>
    <h2>We'll do the swiping for you using our algorithm (based on your likes).</h2>
    <%= simple_form_for(@user) do |f| %>
      <%= f.input :email_address, label: false, placeholder: "Email Address" %>
      <%= f.submit "Subscribe" %>
    <% end %>
  </div>
  <%= image_tag 'nomatchesontinder.png' %>
</div>

<div class="footer">
  <a href="https://www.hoxton-digital.com">London Web Development</a>
  <%= link_to 'Privacy Policy', privacypolicy_path  %>
</div>